/**
 * ics.ts
 *
 * Generates standard iCalendar (.ics) files from the recovery arc timestamps.
 * The recovery window is represented as a calendar event so users can add it
 * to their preferred calendar app (Apple Calendar, Google Calendar, Outlook).
 *
 * Usage:
 *   const icsContent = generateRecoveryIcs({
 *     verdict: "Your body is in damage control.",
 *     recoveryTime: "6pm tonight",
 *     recoveryArc: { dangerEnds, partialEnds, clearedAt },
 *   });
 *   downloadIcs(icsContent, "body-debt-recovery.ics");
 */

import type { DebtAnalysis } from "@/lib/types";

// ─── ICS content generation ──────────────────────────────────────────────────

interface RecoveryEventInput {
  verdict: string;
  recoveryTime: string;
  recoveryArc: DebtAnalysis["recoveryArc"];
  appName?: string;
}

/**
 * Build a complete .ics file string from the recovery arc.
 *
 * Event window: dangerEnds → clearedAt (the full recovery journey).
 * The verdict is used as the event description.
 */
export function generateRecoveryIcs(input: RecoveryEventInput): string {
  const { verdict, recoveryArc, appName = "Body Debt Recovery" } = input;
  const now = new Date();
  const dtStamp = formatIcsDate(now);

  const dtStart = new Date(recoveryArc.dangerEnds);
  const dtEnd = new Date(recoveryArc.clearedAt);

  // iCalendar requires CRLF line endings and lines < 75 octets.
  // Fold long lines with \r\n<space> continuation.
  const summary = foldLine(`Recovery Window — ${appName}`);
  const description = foldLine(
    `Recovery status: ${verdict}\n` +
    `Cleared by: ${input.recoveryTime}\n` +
    `Generated by bodydebt.app`
  );

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Body Debt//Recovery Calendar//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "BEGIN:VEVENT",
    `UID:body-debt-recovery-${dtStamp}@bodydebt.app`,
    `DTSTAMP:${dtStamp}`,
    `DTSTART:${formatIcsDate(dtStart)}`,
    `DTEND:${formatIcsDate(dtEnd)}`,
    `SUMMARY:${summary}`,
    `DESCRIPTION:${description}`,
    "STATUS:CONFIRMED",
    "TRANSP:OPAQUE",
    "BEGIN:VALARM",
    "TRIGGER:-PT1H",
    "ACTION:DISPLAY",
    "DESCRIPTION:Reminder: check your recovery progress",
    "END:VALARM",
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\r\n") + "\r\n";
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Format a Date as iCalendar local time (no timezone — floating time).
 * Format: YYYYMMDDTHHMMSS
 */
function formatIcsDate(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    date.getFullYear() +
    pad(date.getMonth() + 1) +
    pad(date.getDate()) +
    "T" +
    pad(date.getHours()) +
    pad(date.getMinutes()) +
    pad(date.getSeconds())
  );
}

/**
 * Fold a line to <75 octets per iCalendar spec (RFC 5545 §3.1).
 * Long lines are continued on the next line with a leading space.
 */
function foldLine(line: string): string {
  const maxLen = 74;
  if (line.length <= maxLen) return line;

  const parts: string[] = [];
  let pos = 0;
  while (pos < line.length) {
    const chunk = line.slice(pos, pos + maxLen);
    if (pos === 0) {
      parts.push(chunk);
    } else {
      parts.push(" " + chunk);
    }
    pos += maxLen;
  }
  return parts.join("\r\n");
}

// ─── Browser download ────────────────────────────────────────────────────────

/**
 * Trigger a browser download of the .ics file.
 * Works in all modern browsers.
 */
export function downloadIcs(content: string, filename = "body-debt-recovery.ics"): void {
  if (typeof window === "undefined") return;

  const blob = new Blob([content], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();

  // Cleanup
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}
