"""
Publish Body Debt dataset and model weights to Kaggle.

Kaggle doesn't have a model hub — weights are uploaded as Kaggle
"datasets". This script handles both the fine-tuning dataset and
the fine-tuned model weights.

Prerequisites:
    1. Install kaggle CLI: pip install kaggle
    2. Place your Kaggle API token at ~/.kaggle/kaggle.json
       (Get it from: https://www.kaggle.com/settings → API → Create New Token)
    3. Register your Kaggle credentials in Adaption:
       https://adaptionlabs.ai/app/settings?tab=api_keys

Usage:
    # Publish the fine-tuning dataset
    python publish_kaggle.py --dataset

    # Publish fine-tuned model weights
    python publish_kaggle.py --weights --model-dir path/to/fine-tuned-model

    # Publish both
    python publish_kaggle.py --dataset --weights --model-dir path/to/model

    # Publish the augmented dataset (AutoScientist Challenge)
    python publish_kaggle.py --augmented
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).parent
DATASETS_DIR = HERE / "datasets"

# Kaggle dataset slugs (change via env vars)
DATASET_SLUG = os.environ.get("KAGGLE_DATASET_SLUG", "udirobert/body-debt-finetune-dataset")
WEIGHTS_SLUG = os.environ.get("KAGGLE_WEIGHTS_SLUG", "udirobert/body-debt-llama32-3b-autoscientist")
AUGMENTED_SLUG = os.environ.get("KAGGLE_AUGMENTED_SLUG", "udirobert/body-debt-autoscientist-dataset")

AGENTS = ["triage", "coach", "schedule", "reflection"]


def check_kaggle_credentials() -> None:
    """Verify that Kaggle credentials are available."""
    token_path = Path.home() / ".kaggle" / "kaggle.json"
    if not token_path.exists():
        raise SystemExit(
            f"Missing Kaggle API token at {token_path}.\n"
            "Get it from: https://www.kaggle.com/settings → API → Create New Token\n"
            "Place it at ~/.kaggle/kaggle.json"
        )
    # Check kaggle CLI is installed
    try:
        subprocess.run(["kaggle", "--version"], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        raise SystemExit(
            "kaggle CLI not found. Install with: pip install kaggle"
        )


def ensure_dataset_readme() -> Path:
    """Generate a dataset-metadata.json for the fine-tuning dataset."""
    meta_path = DATASETS_DIR / "dataset-metadata.json"
    if meta_path.exists():
        return meta_path

    # Parse slug: "username/dataset-name"
    parts = DATASET_SLUG.split("/")
    if len(parts) != 2:
        raise SystemExit(f"Invalid KAGGLE_DATASET_SLUG: {DATASET_SLUG} (expected 'user/slug')")

    meta = {
        "title": "Body Debt Fine-Tuning Dataset",
        "id": DATASET_SLUG,
        "licenses": [{"name": "APACHE-2.0"}],
        "isPrivate": False,
        "description": (
            "Structured recovery prescription dataset for fine-tuning small "
            "language models on the Body Debt 4-agent health coaching pipeline. "
            "Contains 12,800 chat-formatted examples (3,000 train + 200 test "
            "per agent × 4 agents: Triage, Coach, Schedule, Reflection). "
            "Generated by a deterministic physiological scoring engine with "
            "template-based labels. Built for the Adaption AutoScientist Challenge."
        ),
        "keywords": ["healthcare", "fine-tuning", "structured-output", "recovery", "autoscientist"],
    }
    meta_path.write_text(json.dumps(meta, indent=2))
    print(f"  Generated {meta_path.name}")
    return meta_path


def publish_dataset() -> None:
    """Upload the fine-tuning dataset JSONL files to Kaggle."""
    if not DATASETS_DIR.exists():
        raise SystemExit(
            f"Missing {DATASETS_DIR}. Run `python generate_finetune_dataset.py` first."
        )

    # Check files exist
    missing = []
    for agent in AGENTS:
        for split in ["train", "test"]:
            f = DATASETS_DIR / f"{agent}_{split}.jsonl"
            if not f.exists():
                missing.append(f.name)
    if missing:
        raise SystemExit(f"Missing dataset files: {', '.join(missing)}")

    ensure_dataset_readme()

    print(f"Uploading dataset to Kaggle: {DATASET_SLUG}")
    print(f"  Files: {DATASETS_DIR}/")

    # Try to create the dataset first; if it exists, push a new version
    result = subprocess.run(
        ["kaggle", "datasets", "create", "-p", str(DATASETS_DIR), "--dir-mode", "zip"],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        if "already exists" in result.stderr.lower() or "409" in result.stderr:
            print("  Dataset exists, creating new version...")
            result = subprocess.run(
                ["kaggle", "datasets", "version", "-p", str(DATASETS_DIR), "--dir-mode", "zip"],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                raise SystemExit(f"Failed to version dataset:\n{result.stderr}")
        else:
            raise SystemExit(f"Failed to create dataset:\n{result.stderr}")

    print(f"  Done. View at: https://www.kaggle.com/datasets/{DATASET_SLUG}")


def publish_weights(model_dir: str) -> None:
    """Upload fine-tuned model weights to Kaggle as a dataset."""
    model_path = Path(model_dir)
    if not model_path.exists():
        raise SystemExit(f"Model directory not found: {model_path}")

    # Create a temp staging dir with metadata
    staging = model_path / "dataset-metadata.json"
    parts = WEIGHTS_SLUG.split("/")
    if len(parts) != 2:
        raise SystemExit(f"Invalid KAGGLE_WEIGHTS_SLUG: {WEIGHTS_SLUG}")

    meta = {
        "title": "Body Debt Llama-3.2-3B AutoScientist Fine-Tuned",
        "id": WEIGHTS_SLUG,
        "licenses": [{"name": "APACHE-2.0"}],
        "isPrivate": False,
        "description": (
            "Fine-tuned Llama-3.2-3B-Instruct (LoRA) for the Body Debt 4-agent "
            "health recovery pipeline (Triage, Coach, Schedule, Reflection). "
            "Trained with Adaption AutoScientist on the augmented Body Debt "
            "dataset. LoRA r=32, alpha=64, 3 epochs, SFT. Built for the "
            "Adaption AutoScientist Challenge (Healthcare category)."
        ),
        "keywords": ["healthcare", "fine-tuning", "llama", "lora", "structured-output", "autoscientist", "adaption"],
    }
    staging.write_text(json.dumps(meta, indent=2))

    print(f"Uploading weights to Kaggle: {WEIGHTS_SLUG}")
    print(f"  Model dir: {model_path}/")

    result = subprocess.run(
        ["kaggle", "datasets", "create", "-p", str(model_path), "--dir-mode", "zip"],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        if "already exists" in result.stderr.lower() or "409" in result.stderr:
            print("  Dataset exists, creating new version...")
            result = subprocess.run(
                ["kaggle", "datasets", "version", "-p", str(model_path), "--dir-mode", "zip"],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                raise SystemExit(f"Failed to version weights:\n{result.stderr}")
        else:
            raise SystemExit(f"Failed to create weights dataset:\n{result.stderr}")

    print(f"  Done. View at: https://www.kaggle.com/datasets/{WEIGHTS_SLUG}")


def publish_augmented() -> None:
    """Upload the AutoScientist-augmented dataset to Kaggle."""
    jsonl_path = DATASETS_DIR / "augmented_train.jsonl"
    csv_path = DATASETS_DIR / "augmented_combined.csv"

    if not jsonl_path.exists():
        raise SystemExit(
            f"Missing {jsonl_path}. Download the augmented dataset from Adaption first."
        )

    # Create metadata
    meta_path = DATASETS_DIR / "dataset-metadata-augmented.json"
    parts = AUGMENTED_SLUG.split("/")
    if len(parts) != 2:
        raise SystemExit(f"Invalid KAGGLE_AUGMENTED_SLUG: {AUGMENTED_SLUG}")

    meta = {
        "title": "Body Debt AutoScientist Dataset (Augmented)",
        "id": AUGMENTED_SLUG,
        "licenses": [{"name": "APACHE-2.0"}],
        "isPrivate": False,
        "description": (
            "Augmented fine-tuning dataset for the AutoScientist Challenge "
            "(Healthcare category). Contains 5,462 instruction-tuning examples "
            "for a 4-agent health recovery coaching pipeline (Triage, Coach, "
            "Schedule, Reflection). Generated by a deterministic physiological "
            "scoring engine, then augmented with Adaption Adaptive Data (prompt "
            "rephrasing, reasoning traces, deduplication). Quality improved from "
            "7.0 to 9.23 (+31.9%). Trained with AutoScientist on Llama-3.2-3B "
            "with LoRA (r=32, alpha=64, 3 epochs)."
        ),
        "keywords": ["healthcare", "fine-tuning", "structured-output", "recovery", "autoscientist", "adaption", "llama"],
    }
    meta_path.write_text(json.dumps(meta, indent=2))
    print(f"  Generated {meta_path.name}")

    print(f"Uploading augmented dataset to Kaggle: {AUGMENTED_SLUG}")
    print(f"  Files: {DATASETS_DIR}/")

    # Kaggle CLI uses dataset-metadata.json in the directory
    # We need to use the augmented metadata
    kaggle_meta = DATASETS_DIR / "dataset-metadata.json"
    kaggle_meta_backup = DATASETS_DIR / "dataset-metadata-backup.json"

    # Backup existing metadata if present
    if kaggle_meta.exists():
        kaggle_meta.rename(kaggle_meta_backup)

    # Use augmented metadata
    import shutil
    shutil.copy(meta_path, kaggle_meta)

    try:
        result = subprocess.run(
            ["kaggle", "datasets", "create", "-p", str(DATASETS_DIR), "--dir-mode", "zip"],
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            if "already exists" in result.stderr.lower() or "409" in result.stderr:
                print("  Dataset exists, creating new version...")
                result = subprocess.run(
                    ["kaggle", "datasets", "version", "-p", str(DATASETS_DIR), "--dir-mode", "zip"],
                    capture_output=True,
                    text=True,
                )
                if result.returncode != 0:
                    raise SystemExit(f"Failed to version dataset:\n{result.stderr}")
            else:
                raise SystemExit(f"Failed to create dataset:\n{result.stderr}")
    finally:
        # Restore original metadata
        kaggle_meta.unlink()
        if kaggle_meta_backup.exists():
            kaggle_meta_backup.rename(kaggle_meta)

    print(f"  Done. View at: https://www.kaggle.com/datasets/{AUGMENTED_SLUG}")


def main():
    parser = argparse.ArgumentParser(description="Publish Body Debt artifacts to Kaggle")
    parser.add_argument("--dataset", action="store_true", help="Publish the fine-tuning dataset")
    parser.add_argument("--augmented", action="store_true", help="Publish the augmented AutoScientist dataset")
    parser.add_argument("--weights", action="store_true", help="Publish fine-tuned model weights")
    parser.add_argument("--model-dir", default=None, help="Path to fine-tuned model directory")
    args = parser.parse_args()

    if not args.dataset and not args.weights and not args.augmented:
        parser.error("Specify at least one of --dataset, --augmented, or --weights")

    check_kaggle_credentials()

    if args.dataset:
        print("\n=== Publishing Dataset ===")
        publish_dataset()

    if args.augmented:
        print("\n=== Publishing Augmented Dataset ===")
        publish_augmented()

    if args.weights:
        if not args.model_dir:
            parser.error("--weights requires --model-dir")
        print("\n=== Publishing Weights ===")
        publish_weights(args.model_dir)

    print("\nAll done. Don't forget to also publish to Hugging Face:")
    print("  python publish_finetune_dataset.py")


if __name__ == "__main__":
    main()
